### ISSUE TITLE
Cannot change wifi settings after initial setup

### ISSUE THREAD

**Issue by drstikko** [rvdbreemen/OTGW-firmware#100]
After connecting to the device (mine is Wemos D1 mini pro) in AP mode after flashing, one selects the SSID/password for local network connection. Unfortunately it seems it cannot be changed afterwards (maybe I overlooked something). This can be unhandy when for example the wifi password of the router changes.

**Comment by DaveDavenport** [comment]
I think if your wifi password change and you reboot (reset) the wemos it should go into the original ap mode.
(I agree a option in the UI would be nice.)

**Comment by drstikko** [comment]
Actually, in my case, I want to move it to another access point. So now, it keeps connecting to the 'old' one. I thought actually going to the setup link could work? But I don't have it in my history.

**Comment by rvdbreemen** [comment]
The easiest way to re-configure the wifi is to simply turnoff or change the password on the wifi accesspoint it is connecting too. 

That way it will reconfigure enter the configuration mode once more. 

It's on my longlist to improve this. But this is the work around for now.

**Comment by DaveDavenport** [comment]
@rvdbreemen  maybe we can add a button that calls:

```C++
WiFiManager::resetSettings();
```
or even just starts the portal?

**Comment by rvdbreemen** [comment]
Yep, that's the idea. Just reset the settings...

**Comment by drstikko** [comment]
sounds good

**Comment by DaveDavenport** [comment]
Added an PR: #101

**Comment by rvdbreemen** [comment]
Will include reset button in next release.

**Comment by rvdbreemen** [comment]
Fixed in release 0.9.2
