### ISSUE TITLE
Send less data

### ISSUE THREAD

**Issue by phoenix-blue** [rvdbreemen/OTGW-firmware#11]
Hi,

I have flash the Otgw with this version to interact with HomeAssistant. 
I see in the MQTT broker a lot of traffic from the OTGW. 
Is there an option to for example remove first the data points that are not available from the Opentherm data?

**Comment by rvdbreemen** [comment]
@phoenix-blue so the traffic you initially see is the MQTT Discovery, it sends message to the Home Assistant discovery topics.
These message are used to automatically configure the Home Assistant sensors, so you do not need to setup any templates yourself.

But if you do not use Home Assistant, or just want to turn off the MQTT Discovery feature. Then you can safely delete the `mqttha.cfg` from the SPIFF memory.

All other messages that are send to MQTT are messages the OTGW sees. I support ALL messageids from the OT specification 2.2 + 2.3b, and some more features specific to Remeha.

Did this help you?
