### ISSUE TITLE
Too small password length for MQTT

### ISSUE THREAD

**Issue by suenio** [rvdbreemen/OTGW-firmware#12]
I'm using default passwords generated by MQTT Broker integration in HomAssistant. Is there a chance to extend length of MQTT password to something like 96 characters?

**Comment by rvdbreemen** [comment]
@suenio I see no problem with a longer password. Didn't know there was a good case for it. Now I know better.
I will add it to the todo list.

**Comment by rvdbreemen** [comment]
fixed in release v0.7.5, up to 100 chars for your mqtt password
