### ISSUE TITLE
Use D8 for DS18B20 prevents boot

### ISSUE THREAD

**Issue by fhennies** [rvdbreemen/OTGW-firmware#123]
I just discovered that using D8 (GPIO 15) toconenct a DS18B20 with the recommended pull-up prevents boot. I haven't investigated much further, but it seems that GPIO 15 is involved in bootmode selection at start-up. Maybe the wiki could be updated with this information: https://github.com/rvdbreemen/OTGW-firmware/wiki/Using-DS18B20-sensor-with-ESP-firmware

**Comment by rvdbreemen** [comment]
@fhennies thanks for reporting the issue. I removed D8 from the documentation.
