### ISSUE TITLE
Wiki: Flashing not working with Espressif Flash Tool 3.9.3

### ISSUE THREAD

**Issue by ministryofsillywalks** [rvdbreemen/OTGW-firmware#136]
I followed the wiki on installing via ui.
Following the link Espressif only offers the download of the flash tool in version 3.9.3.
Using that version the flash keeps failing.
I had to dig around the internet for the older version flash_download_tool_3.8.5.exe which worked instantly.

**Comment by STemplar** [comment]
I got the same problem and also used an older version of the software (3.8.8).
The interface has changed a bit.
![afbeelding](https://user-images.githubusercontent.com/23719607/206932719-42756efa-1c1b-4670-9ed2-274327902f82.png)

**Comment by rvdbreemen** [comment]
Flahsing of v.0.10.0 should work once more. Even with the flash UI.
