### ISSUE TITLE
White screen on Wifi Configure

### ISSUE THREAD

**Issue by 0000vt** [rvdbreemen/OTGW-firmware#139]
Please remove… need to read wiki first

**Comment by GunnarMorrigan** [comment]
I also ran into this issue. What is the wiki article that helped?

**Comment by 0000vt** [comment]
Not sure, don’t remember. Make sure you follow all steps one by one.

**Comment by GunnarMorrigan** [comment]
I restarted the Wemos d1 mini via the reset button and revisited the page. This time it loaded the wifi page without being blank!

Thanks for the fast response @0000vt
