### ISSUE TITLE
wifi page empty after flash

### ISSUE THREAD

**Issue by bgrr74** [rvdbreemen/OTGW-firmware#142]
FYI.

When flashing new Wemos D1 mini with version 21 (OTGW-firmware.0.9.5+4eb7d24.ino.bin) the wif settings page is empty when Wemos  restarts in AP mode.

As work around i flashed the wemos with version 19 (OTGW-firmware.ino.0.9.3+b4b8026.bin). Then the wifi page is working without problems in AP mode and i was able to connect the Wemos to my home wifi.

Upgrade from V19 to V21 worked without problems once the wemos is connected to the home wifi.

Greetings

**Comment by rvdbreemen** [comment]
Hi

Thanks for reporting and for finding a work around. 

How totally weird. I have to check into what changed over time and if there is a logical explanation. 

Regards
Robert

**Comment by tuxick** [comment]
Same problem here.

**Comment by Sidhy** [comment]
I can confirm both info and WiFi page stays blank when flashing latest firmware, thanks for the hint using a different firmware will test this first,

**Comment by DaniilMir** [comment]
@bgrr74 Thank you for posting a workaround !!! 
It helped me to stop hating D1 module which was not working properly with WiFi page.

**Comment by tjfsteele** [comment]
I have also experienced this.

**Comment by rvdbreemen** [comment]
I have experienced it myself. When switching to a new location, thus changing AP. I had to "wipe" the flash completely to get it working properly. So I will add erase_flash on the installation instruction, so it will always wipe the flash. That way we know for sure that on following the instructions to install the firmware + filesystem, all flash is wipes, including the wifi settings.
