### ISSUE TITLE
OEM Fault code is shown as Boolean instead of number

### ISSUE THREAD

**Issue by chokays** [rvdbreemen/OTGW-firmware#144]
Both OTMonitor (OEM Fault code) as the display of my CV Heater show code 105.

Webinterface of OTGW shows:
OEM Diagnostic code: 126
OEM Fault code: true

Is this expected behavior?

**Comment by rvdbreemen** [comment]
It's a known issue. It's a bug in my code I need to fix it. 😬

**Comment by rvdbreemen** [comment]
Fixed in next release 0.10.0
