### ISSUE TITLE
Unexpected spikes in MQTT values Water pressure and Relative Modulation level 

### ISSUE THREAD

**Issue by chokays** [rvdbreemen/OTGW-firmware#145]
![image](https://user-images.githubusercontent.com/95276985/200130822-27e2a702-a6fa-401e-9f30-f5fe1539b0f9.png)
![image](https://user-images.githubusercontent.com/95276985/200130839-3b462ce2-fce6-4bb2-b3e9-40c266c29198.png)
![image](https://user-images.githubusercontent.com/95276985/200130880-18b11e87-fe2a-434f-8599-182d69609c0c.png)

There are some spikes in the MQTT data shown in Home Assistant for the water pressure and relative modulation level.

OTMonitor does not show these spikes.

**Comment by rvdbreemen** [comment]
You did also report with logging. That helps understanding, but not explaining what is going on. Would you be able to log in full details (with MQTT logging turned on, goto firmware with telnet, and then hit '3'). And see if we can catch the issue in plain sight.

**Comment by chokays** [comment]
Duplicate and also fixed

**Comment by chokays** [comment]
Duplicate and also fixed
