### ISSUE TITLE
[Request] rename MQTT prefix for better clarity

### ISSUE THREAD

**Issue by 0crap** [rvdbreemen/OTGW-firmware#160]
If you use the MQTT option and configure it under "Advanced->OTGW Settings" the prefix box can have a better description.

Now the item is called `MQTT Home Assistant prefix`.
![MQTT prefix](https://user-images.githubusercontent.com/31951195/212492794-ee48d802-e2a2-42d8-a505-348cbf45d272.png)

Looking from the MQTT side of it, this is in fact the `MQTT Auto Discovery Prefix`.
Which seems a better and more accurate description for this box.

Not only Home Assistant but also other home automation software, like Domoticz, can use the OTGW.
So for first time OTGW users, keeping the current name might be confusing.

For backwards compatibility it seems an idea to keep the default value at `homeassistant`.
But you might consider to leave this field empty by default.

**Comment by rvdbreemen** [comment]
Will be changed in next release.
