### ISSUE TITLE
Adding block boiler Option 

### ISSUE THREAD

**Issue by phoenix-blue** [rvdbreemen/OTGW-firmware#207]
Currently, the gateway / boiler operates based on demand from the indoor temperature sensor/thermostat. However, I would like to request the addition of an option that allows the boiler to be blocked based on the outdoor air sensor.
So when the boiler is blocked there must be enabled an digital output for an heatpump so the Gateway can be used for an hybride/bivalent heatpump solution.

**Comment by rvdbreemen** [comment]
@phoenix-blue i think you should use a home automation solution for this. You could use home assistant to react based on the temperature reported and control your boilers or heat pump accordingly. 

Don’t thin this a feature for the OTGW itself.
