### ISSUE TITLE
Wiki - How to use it .... Homey now supported too!

### ISSUE THREAD

**Issue by gruijter** [rvdbreemen/OTGW-firmware#210]
https://github.com/rvdbreemen/OTGW-firmware/wiki/How-to-use-it-with-Home-Assistant-or-Domoticz-or-others

Could you add Homey as a supported platform? I posted instructions on how to use with Homey here:
https://community.homey.app/t/77190

Thx for your work!

**Comment by rvdbreemen** [comment]
@gruijter thank you for adding support. I have added it to the wiki documentation, thanks for building the support for Homey and adding value to this eco-system around OpenTherm Gateway.

Robert

**Comment by gruijter** [comment]
Thx!
The newly created link o the WiKi is dead though...

**Comment by rvdbreemen** [comment]
That's because the page changed: 

https://github.com/rvdbreemen/OTGW-firmware/wiki/How-to-use-it-with-Home-Assistant,-Homey-or-Domoticz-or-others

You should be proud I think.

**Comment by rvdbreemen** [comment]
Got it, fixed.

**Comment by rvdbreemen** [comment]
And I will fix the NL version later ;-)
