### ISSUE TITLE
Can't update PIC

### ISSUE THREAD

**Issue by koendiender** [rvdbreemen/OTGW-firmware#213]
When I try to download the new OTGW PIC version (6.5) to the ESP the size shows 0. After I then try to flash this firmware, it still shows version 6.4 as the installed PIC firmware version.

<img width="1022" alt="image" src="https://user-images.githubusercontent.com/9695378/224975650-528ac1ee-9a8f-4576-b614-4927b582466b.png">

**Comment by rvdbreemen** [comment]
Thanks for reporting it. On the discord channel this was also noted last night. I will look into why this is happening.

**Comment by rvdbreemen** [comment]
Fixed in 0.10.2, out now. Just visit the releases section.
