### ISSUE TITLE
Settings menu not loading

### ISSUE THREAD

**Issue by jcouzy** [rvdbreemen/OTGW-firmware#215]
Hi,

I am a new user of the OTGW which I acquired from Node Shop.
I received it fully programmed including the WiFi module.
I was able to configure WiFi and am able to access the OTGW.
Everything seems to work fine, except the settings menu.
When I click on the settings button, I get the red bar with loading...... in it and it stays this way.

Any clue?
<img width="1096" alt="Screenshot 2023-04-07 at 19 16 42" src="https://user-images.githubusercontent.com/51447772/230650128-19925b0f-0e55-4570-9b08-ae4b2536b138.png">

**Comment by rvdbreemen** [comment]
Did you also flash the filesystem?

**Comment by jcouzy** [comment]
Yes, also reflashed the file system, to be sure there are no custom configuration active which could interfere.

**Comment by rvdbreemen** [comment]
So can you use the file explorer (right navigation menu) to check to see if you can find the setting.ini file.

**Comment by rvdbreemen** [comment]
How did it go @jcouzy ?

**Comment by jcouzy** [comment]
I was able to download, modify and upload the file, but it looks like the setting changes don't get activated.
I get the assumption that the WiFi module is very unstable.

**Comment by rvdbreemen** [comment]
@jcouzy did you ever look at the debug menu, it tells you the WiFi quality.
