### ISSUE TITLE
Domoticz gives multiple Connection reset messages

### ISSUE THREAD

**Issue by 0crap** [rvdbreemen/OTGW-firmware#222]
Domoticz Log gives multiple random "Connection reset!" messages.
![Domoticz-Log](https://github.com/rvdbreemen/OTGW-firmware/assets/31951195/0180c833-2e88-4935-8388-5f9d5edc2c35)

Not sure what the trigger is for it to happen.
The OTGW for sure does not reboot.
Because if that happens the Domoticz Log gives much more info.
Also the OTGW "Nr. Reboots" is on 4 for a long time. (And does not increase.)
![OTGW](https://github.com/rvdbreemen/OTGW-firmware/assets/31951195/93e77e41-4776-4e56-b9a8-ddc2ef707cc4)

**Comment by Nifrabar** [comment]
I recently installed the new software on the old OTGW.
Alle devices are automaticly found by Domoticz via MQTT.  Monitoring is perfect but control is not. Not able to set the override temperature. 
Meanwhile als the error 19 appears about once ever 6 minutes: Connection lost , restarting.

**Comment by rvdbreemen** [comment]
Interesting. Your OTGW should not just reset. Have you looked at the reset count in the webUI? It might just be a mqtt reconnect.

**Comment by Nifrabar** [comment]
Robert, no reboot but disconnect <> connect which imho is something else.

**Comment by rvdbreemen** [comment]
The firmware does auto reconnect when it loses the MQTT hub connection for any reason. The 6 minute cycle is too constant to be random, so it must be something else. 

However I do not run Domoticz. So I cannot recreate this issue. 

Closing unless someone help to reproduce.
