### ISSUE TITLE
Cannot upgrade firmware

### ISSUE THREAD

**Issue by avvjunk** [rvdbreemen/OTGW-firmware#223]
I have an OpenTherm Gateway from November 2021 with a wifi module (NodeMCU ??) and I would like to update it with the latest firmware. The process is not completely clear to me and I have some questions about it.

I checked the physical chip in the OTGW to find the version (P16F88) because I could not find that info anywhere in the GUI. Is that info available from the GUI and if so, where can I find that?

When I connect to the OpenThermGTW from a browser, I land on a page titled "Welcome to ESP Easy: OpenThermGTW" that shows the following info:

Load:	5% (LC=32077)
Uptime:	75 minutes
Wifi RSSI:	-65 dB
IP:	192.168.110.71
GW:	192.168.110.1
Build:	147
Core Version:	2_3_0
Unit:	1
STA MAC:	44:17:93:20:02:fa
AP MAC:	        46:17:93:20:02:fa
ESP Chip ID:	2097914
Flash Chip ID:	1458270
Flash Size:	4096 kB
Flash Writes (since boot):	6
Sketch Size/Free:	421 kB / 600 kB
Free Mem:	26880
Devices:	35
Boot cause:	Manual reboot

OTMonitor gives the following info: "The OTGW is currently running unknown firmware."

What does the Core Version: 2_3_0 mean? I do not see a version 2.3.0 in http://otgw.tclcode.com/download.html. Is that an outdated version that is not longer available for download? 

https://github.com/rvdbreemen/OTGW-firmware states that I should not use OTMonitor to upgrade the firmware. I should use the "buildin PIC firmware upgrade feature". It is not clear to me what the buildin upgrade firmware feature is exactly. Is that the "Firmware Load" button on the Tools tab of the Web interface? (http://<IP-Address OTGW>/update)

When I try to upload "gateway.hex" from there and click update, I just get "Update Failed!"

Despite the warning not to use OTMonitor, I decided to try that anyway.

When I click the "Program" button the the "Firmware Upgrade" dialog in OTMonitor, after selecting "gateway.hex" and with OTMonitor connected to the OTGW, I get the message "Please manually reset the OpenTherm Gateway". What am I supposed to do here? I tried a power cycle of the OTGW, but that did not work. After some time, OTMonitor gives the message "Could not switch gateway to self-programming mode"

I also tried the "selfprogupd.hex" but that resulted in the following message:
Invalid firmware file: expected hexadecimal string but got "020000040000FA" instead

It would be great to have some step by step instructions for the firmware upgrade process, but I could not find that. Are such instructions available somewhere?

**Comment by rvdbreemen** [comment]
This github repo is about my ESP firmware, called OTGW-firmware. It build it to replace the ESPeasy software that originally was used by a lot of people to implement a serial2network bridge using the ESPeasy software. 

So @avvjunk, it sounds like you are still using the original ESPlink software. If you want to upgrade your PIC you can use my ESP firmware, that includes that feature for you.

The ESP OTGW firmware I have written has implemented features like: 
- integration with home assistant, and other home automation software using MQTT
- update the PIC firmware for the different types of PICs
- and many more things.

If you want to upgrade your PIC on the OTGW hardware, then you should flash the ESP with my firmware, and then in the WebUI provided you can find the upgrade PIC feature.

The documentation can be found here:
https://github.com/rvdbreemen/OTGW-firmware/wiki

It includes all instructions you need to flash the firmware onto your ESP, and the to update your PIC firmware as well. 

Need any support? Then join the discord community, we are there to help you with any steps along the way.

Kinds regards,
Robert
