### ISSUE TITLE
OTGW OTA firmware upgrade failed

### ISSUE THREAD

**Issue by infoedkok** [rvdbreemen/OTGW-firmware#228]
Hoi,
With OTMONITOR, trying to upgrade firmware from 4.2.5. to 4.3.

Connecting to the gateway is succesfull, I see values in the monitor

It doesn't work: it showes message "firmware upgrade failed- 0 errors".
No entry in the logfile.
![image](https://github.com/rvdbreemen/OTGW-firmware/assets/116073652/beed1b9a-64ca-4e23-9985-34d6d0d917fb)

What could be the reason?

Regards, Ed

**Comment by rvdbreemen** [comment]
Hi Ed

Just login into the webUI and use the OTGW firmware on the ESP to upgrade the PIC in the OTGW. 

That will work. Is there a reason you want to just upgrade to 4.3? As there is 5.x out for you hardware. 

Hope this helps,
Robert

**Comment by rvdbreemen** [comment]
Closed due to inactivity.
