### ISSUE TITLE
Feature: expose current DHW tank temperature to MQTT

### ISSUE THREAD

**Issue by vbartusevicius** [rvdbreemen/OTGW-firmware#233]
Heating domestic hot water takes time, it is useful to see the current DHW tank temperature. 

It could also save some time on debugging why DHW function is not heating - apparently the setpoint in the water tank is already reached.

**Comment by rvdbreemen** [comment]
@vbartusevicius please give move information, I don't understand. I will close this issue, you may reopen if you provide more information
