### ISSUE TITLE
Firmware of V2 hardware 

### ISSUE THREAD

**Issue by roblomq** [rvdbreemen/OTGW-firmware#241]
I've bought a second hand version of the OTGW V2 from Nodo-shop. It seems to work but I get the error "Error: OTGW: Error received!: " in my Domoticz. Now I first want to start by updating the firmware but I'm unsure how. 
My current mainscreen is as follow.
![ScreenHunter_45 Feb  11 14 22](https://github.com/rvdbreemen/OTGW-firmware/assets/59142034/112784c9-e301-4714-9850-26e3c03bea62)

1. Is it correct that the right firmware for this is located [here ](https://github.com/rvdbreemen/OTGW-firmware/releases)?
2. In the "Tools" "Firmware Update" there is only one "select file" button, while in the [instructions ](https://github.com/rvdbreemen/OTGW-firmware/wiki/Upgrade-to-new-release-using-Over-The-Air-flashing)there are 2 buttons. Is this because the current version is old or am I completely wrong here?
3. How can I debug this to find the reason it is giving the errors?

**Comment by rvdbreemen** [comment]
Follow the instructions on the wiki how to install: https://github.com/rvdbreemen/OTGW-firmware/wiki/How-to-install-firmware-on-your-ESP

I noticed in the screengrab you installed EasyESP. Do not try to update using that. I have not tested  an upgrade using EasyESP. 

The lastest release is currently #24 you found on the GitHub. 

Hope you can flash your OTGW with ESP. 

Regards
Robert
