### ISSUE TITLE
ESP not connecting to WiFi

### ISSUE THREAD

**Issue by ministryofsillywalks** [rvdbreemen/OTGW-firmware#248]
I just reflashed my ESP with the latest version and it just won't connect to wifi.
The WiFiManager shows up as expected after the flash and I can select the desired network. 
However after saving the connection the esp doesn't connect to the network and instead goes back to AP mode.
I have tried different networks but nothing works.
I completely erased the flash and reinstalled but it didn't help.

In the WiFiManager it reads:
Not Connected to MY_NETWORK

I tried to access the esp via putty  but it refuses the connection (all while i can access the WiFiManager)

**Comment by ministryofsillywalks** [comment]
esp was broken.
flashed a different esp and now its working

**Comment by Basb1234** [comment]
I have exactly the same problem as ministryofsillywalks. I tried a different ESP, but still the same problem. Both ESP were successfully flashed with the latest firmware.
I bought a new router, but still the same issue. 
Are there certain requirements that the network should comply to? e.g. only 2,4 Ghz, WPA2, ...
