### ISSUE TITLE
GPIO Output as switch entity in home assistant

### ISSUE THREAD

**Issue by bjornmorsman** [rvdbreemen/OTGW-firmware#252]
Hello,

is it possible to have a relay that is configured as a gpio output in the nodemcu not activated by a bit of the boiler but by a switch entity from home assitant? 

I have a boiler with 2 zones, zone 1 is controlled by an opentherm thermostat and zone 2 by an on/off thermostat. 

I would like to control this 2nd zone with a relay via the nodemcu

thank you

**Comment by rvdbreemen** [comment]
Hi @bjornmorsman 

You can switch relays as much as you like based on any information. The easiest way to do that is to use automation options in home assistant to control a relay seperate from the OTGW. Just use the binary readout output to control a relay you need. 

Hope this solves your issue,
Robert
