### ISSUE TITLE
AA command has no effect

### ISSUE THREAD

**Issue by chryss44** [rvdbreemen/OTGW-firmware#254]
Hello,
I use Boiler De-Dietrich MCX 24/28 BIC PLUS with NETATMO and OTGW  on Wemos with last nodo shop board.
I have make all parameters on OpenTherm Monitor and have MQTT server to monitor information.

All Firmwares are in last version :

- OTGW firmware version 0.10.3+e334c42
- diagnose.hex	version 2.1
- gateway.hex	version6.6
- interface.hex	version 2.0
- OpenTherm Monitor Version 6.6
- Gateway (board) V2.11
 
If i just plug my Boiler on OTW, everything is correct and i have all interesting information for me and when i plug Netatmo some informations disappears, normal (when i read notice on http://otgw.tclcode.com/firmware.html#cmdps).
Well, if i want to receive informations what i need, i use AA= command on OpenTherm Monitor and log is correct. 
But nothing appears on the OTWMonitor, and when i use DA= command to delete, some information return not error message, as if information not exist.

I push log with command AA and DA where for example DA=27 repeat 2 time have no error (strange) and DA=25 / DA=28 are a return NF for not found and is normal.
But no return with all this command :-( .

otlwlog.txt join [otlwog.txt](https://github.com/user-attachments/files/17788053/otlwog.txt)

Thanks for your help

**Comment by rvdbreemen** [comment]
Hi @chryss44 

Did you checkout:

http://otgw.tclcode.com/matrix.cgi#boilers

And

http://otgw.tclcode.com/matrix.cgi#thermostats

To validate if your boiler and thermostat actually support the messages you are asking for?

Let me know,
Robert

**Comment by rvdbreemen** [comment]
@chryss44 

If your boiler does not support the message ID then pushing AA is not changing this. 

Also pushing the same AA command with an ID it will cause OTGW to store the same message ID, with no real effect. 

You also point to the PS command, in the PS=1 state there is a default set of parameters sent, that does not mean that your boiler/thermostat actually support the messages IDs. 

Also not sure if you already do, but integration with MQTT on Home Assistant will give you a complete set of parameters that your boiler and thermostat support fully automatically. 

Hope this helps you figuring out what is going on. 


Kind regards, 
Robert

**Comment by hvxl** [comment]
Read about [how the OTGW uses available slots to request additional information](http://otgw.tclcode.com/firmware.html#additional). Your thermostat requests no information that the boiler does not support, so there are no available slots. You will have to free up some slots to allow the OTGW to send its own requests.

**Comment by chryss44** [comment]
It's good, i declare unknown Id 49, 5 and 122 for place 25, 27 and 28.
It's not user friendly to find what i can be replace but i'm arrive.
Perfect, thanks a lot @hvxl .

**Comment by chryss44** [comment]
t's good, i declare unknown Id 49, 5 and 122 for place 25, 27 and 28.
