### ISSUE TITLE
Time is one hour behind

### ISSUE THREAD

**Issue by PvdGulik** [rvdbreemen/OTGW-firmware#26]
Hello,

Is seems that the OTGW-firmware is a hour behind. Due to DST-setting?
I don't know where is get its time from, but all my other ESP's get the right time.
And the boiler time is also correct.

Thank you!

**Comment by rvdbreemen** [comment]
Check your settings page, there you can setup the correct timezone. It does DST correctly.

**Comment by rvdbreemen** [comment]
I reopened, to wait for confirmation that it works correctly. @PvdGulik

**Comment by PvdGulik** [comment]
Sorry, but where in the settings page?
There's no option... See picture.[cid:F6983424-0F20-4DEA-9736-292D7E52AA92]

Thank you!

vriendelijke groet,

Pieter

Op 21 feb. 2021 om 14:17 heeft Robert van den Breemen <notifications@github.com> het volgende geschreven:

﻿

Check your settings page, there you can setup the correct timezone. It does DST correctly.

**Comment by rvdbreemen** [comment]
I think I know what's going on. Sorry about that. In the dev release there is a setting.
And I just found that sometimes there is DST and sometimes it's not.
It's under investigation.

Thanks for reporting this @PvdGulik

**Comment by PvdGulik** [comment]
Solved in v0.7.6, thanks!

**Comment by rvdbreemen** [comment]
fixed in v.0.7.6 and beyond

**Comment by PvdGulik** [comment]
Hello,

It seems that problem is not totally resolved.
This morning (ca. 9:30) after updating to lateste version 7.7,
the NTP timezone was CET,and time was correct.
Now, at 20:30 the timezone has changed by itself to Europe/Amsterdam and is one hour behind again....

**Comment by rvdbreemen** [comment]
Hi @PvdGulik thanks for reporting back. I am hunting that bug, not sure why it is happening. The simpel fact that it changes from CET to Europe/Amsterdam is telling me that it is switching to the default setting, which is now Europe/Amsterdam. 

The one hour behind is really weird, as my timezone is setup exactly the same and reporting the correct time.

Hmmmm, what is going on.

**Comment by rvdbreemen** [comment]
@PvdGulik 

Well, I changed around some stuff in the dev branch. Now it will not try to be smart anymore and detect the timezone. I will now just accept whatever you decide the Timezone is.

Could you please verify this version? Let me know if you need a binary to test it.
Thanks
Robert

**Comment by PvdGulik** [comment]
Yes, no problem to test. Where I can find the new version of the ino.bin?

**Comment by rvdbreemen** [comment]
Here it is:
[OTGW-firmware.ino.bin.zip](https://github.com/rvdbreemen/OTGW-firmware/files/6039111/OTGW-firmware.ino.bin.zip)

**Comment by PvdGulik** [comment]
Hello Robert,

I installed the new bin, set Timezone to CET, and saved.
Time was 1 hour behind. Reboot.
After reboot Timezone is set back to Europe/Amsterdam, but time is correct.
I set timezone back to CET, save but won't reboot.

Report you the results tomorrow.

Pieter

**Comment by PvdGulik** [comment]
Hello Robert,

8:51 Time is still correct, but timezone is back to Europe/Amsterdam.

I'll wait a couple of hours, keep you informed of any changes.

**Comment by rvdbreemen** [comment]
Sounds like it is fixed so far ;-)
