### ISSUE TITLE
Feature Request - LED control

### ISSUE THREAD

**Issue by nygellyndley** [rvdbreemen/OTGW-firmware#31]
Would it be possible to add some control over the LEDs?

I have the Nodo OTGW in the clear case + NodeMCU.  There are 3 LEDs that flash non-stop, one green one on the board and two blue ones on the MCU.

The green one isn't so bad but the two NodeMCU ones are pretty aggressive.

Perhaps some option to disable the flashing, or reduce the brightness or  rate?

**Comment by rvdbreemen** [comment]
@nygellyndley you can turn off the blue ones simply by going into settings "Heartbeat LED (on/off)". Just uncheck this setting and the two blue leds are turned off. You will miss out on troubleshoot information and the heatbeat. But in some cases that's fine.

To turn off the other led (like the green one), use the PR=L command.
