### ISSUE TITLE
Webpages setting page stay's empty. 

### ISSUE THREAD

**Issue by Marcello1970** [rvdbreemen/OTGW-firmware#4]
The software is working, I see the values in in the MQTT broker. About one thing i'm not clear, the webpages: 
What can I do with the the web pages? The main pages shows 'Wait! retrieving local messages .....' The settings page shows noting. There is a setting.ini file created, but it only contains the host name. Only the 'FSexplorer ESP' works. Is that right?

**Comment by rvdbreemen** [comment]
That correct. The settings stuff and the webpages / UI still need to be done, these are the defaults. I am considering to use ESP Dash v3. But that needs some refactoring to an async library set. But once that's done the UI should be lovely too ;-)

**Comment by rvdbreemen** [comment]
It's a work in progress. The settings code and UI are still not done. Keep tracking the project it will happen.

**Comment by rvdbreemen** [comment]
@Marcello1970 the setting page is done.  Echt up some sort of UI.
