### ISSUE TITLE
Add NTP hostname

### ISSUE THREAD

**Issue by glsf91** [rvdbreemen/OTGW-firmware#46]
First: complements for your software. It is looking very nice.

Would it be possible to add a configurable NTP hostname?
Or use the gateway address if the NTP server is not reachable.
After a firewall NTP is not working now.

**Comment by rvdbreemen** [comment]
Well, you can just turn off NTP thru the setting if you are running behind a firewall. I’ll consider this a feature request. Because it can be done.

**Comment by rvdbreemen** [comment]
This was fixed in v0.9.0 if I remember correctly.
