### ISSUE TITLE
GPIO Output Uses GPIO Sensors interval

### ISSUE THREAD

**Issue by sjorsjuhmaniac** [rvdbreemen/OTGW-firmware#54]
Right now 'output sensors' use the the GPIO Sensors Interval setting.
https://github.com/rvdbreemen/OTGW-firmware/blob/05df1bdbf92b30836071d51893bc7f50ceb85f9d/OTGW-firmware.ino#L38-L39

Although probably not a real issue, this can cause strange/unexpected behavior. 
I suggest to create a new interval var for the ouputs and remove the TODO line upon completion.

**Comment by rvdbreemen** [comment]
I will check what it the correct lines of code. This needs cleaning up.

**Comment by rvdbreemen** [comment]
Removed the interval completly. It should not be an constant, it should just follow the status bit. I moved the evaloutput() to background task. That way it will always be run, when enabled.
