### ISSUE TITLE
Settings loading forever

### ISSUE THREAD

**Issue by alucryd** [rvdbreemen/OTGW-firmware#58]
Hi, I've got an issue with the settings page. It was working fine at first, but ever since I activated MQTT, it won't load anymore and is stuck on `Loading...`, any idea what's going on?
![image](https://user-images.githubusercontent.com/1561084/119224228-bf113400-bafd-11eb-9bc1-470718bf862b.png)
Tried brave and firefox, same result.

**Comment by rvdbreemen** [comment]
That's weird. Have you rebooted and checked what happens?

**Comment by alucryd** [comment]
Yes I have, I've also tried downloading the settings.ini file, and manually disabled mqtt before uploading it back but that didn't change anything so it may be unrelated after all. No reboot is bringing it back, not a huge deal since we have access to settings.ini, but kind of annoying still.

No error in the console either, it just prints `refreshSettings()`, and then nothing :/ If I call it myself, it returns undefined, so that may be why.

**Comment by rvdbreemen** [comment]
To find out what's going on could you telnet to port 23 to get debug information.  

Please capture the debug log and share it. 

Are you able to connect to your MQTT hub using a tool like MQTT explorer (http://mqtt-explorer.com/)?

When you share the logs I can help debug your issue.

**Comment by alucryd** [comment]
Here's the telnet log, I tried accessing the settings at the same time but nothing jumped out to me: https://paste.xinu.at/EDrHCbm9FVI66WRI/

I have since disabled MQTT and am relying on the serial plugin in Home Assistant which works fine. I can reenable it though if you think you can find out more with MQTT.

**Comment by rvdbreemen** [comment]
This debug log looks just fine, but as you mention without MQTT. If you could try an MQTT configuration again, and then log at the same time. Than we will get the information on what is going on with the MQTT connection. It might just explain what is happening there.

**Comment by rvdbreemen** [comment]
Closing this issue as we never found out what the issue was.
