### ISSUE TITLE
Free pins of NodeMcu [question]

### ISSUE THREAD

**Issue by raf1000** [rvdbreemen/OTGW-firmware#66]
Hello,
I would like to ask which NodeMcu`s pins are not used by OTGW software? 
I want to use a free pin of NodeMcu (and add in the code) to turn on/off the water circulation pump

**Comment by rvdbreemen** [comment]
@raf1000 there is already code to switch on and off any pin based on the status bits from the slave (aka as the boiler or ventilator heating". 

The pins you cannot use are:

//define Nodoshop OTGW hardware
#define OTGW_BUTTON 0   //D3
#define OTGW_RESET  14  //D5
#define OTGW_LED1   2   //D4
#define OTGW_LED2   16  //D0

//external watchdog 
#define EXT_WD_I2C_ADDRESS 0x26
#define PIN_I2C_SDA 4   //D2
#define PIN_I2C_SCL 5   //D1

Hope this helps
Robert
