### ISSUE TITLE
Ds18b20 vs firmware 0.9.0

### ISSUE THREAD

**Issue by pro2call-nl** [rvdbreemen/OTGW-firmware#71]
I have 2 dallas temperature sensors connected to gpio10. After upgrading to 0.9.0 the sensors don't show in mqtt.

I downgraded the .ino file to 0.8.6 and there working again.

**Comment by pro2call-nl** [comment]
the problem has been found.

1. i installed the new INO file
2. i installed the new Littlefs file.

I assumed an reboot has been done automaticly. 

after hitting the reboot button in the littlefs webpage the device connection was lost. 1 power reset and everything was working again.

**Comment by rvdbreemen** [comment]
Ahhh, that's weird, because after a flash the esp is rebooted... so why did it initially not bring back everything... but you fixed it by turning it off and on again.
