### ISSUE TITLE
confused about hardware nodoshop, nodemcu or WeMos

### ISSUE THREAD

**Issue by Ramonlambal** [rvdbreemen/OTGW-firmware#75]
HI,

I am currently ordering the parts to build my own opentherm gateway, using this firmware. 
I am however a little bit confused by the new board (v2.3) of nodoshop. 
There it is mentioned the new board (2.3) runs with a WeMos D1 Mini, instead of the always mentioned NodeMCU on this page. 

Is the current firmware (9.0) supported for the WeMos D1 mini, or should I still get the NodeMcu
to be clear we are talkingg about this: https://www.nodo-shop.nl/nl/home/213-wemos-d1-mini.html (which is recommended by them) or https://www.nodo-shop.nl/nl/home/189-nodemcu.html?search_query=nodemcu&results=2

many thanks in advance!

**Comment by rvdbreemen** [comment]
Hi @Ramonlambal 
Thanks for asking. The new PCB V2.3 supports wemos d1mini and the firmware is compatible with the wemos too. 

So you can use the firmware safely. I will add this to the readme. 

Hope this clears up the confusion,
Robert
