### ISSUE TITLE
OTGW randomly stops

### ISSUE THREAD

**Issue by PuckeyP** [rvdbreemen/OTGW-firmware#89]
Hi,
I'm having a problem with the OTGW - NodeMCU in combination with Remeha Calenta and Remeha iSense.
I'm using NodeRed /Home assistant to control the remote override setpoint.

All has worked well for about three months, but suddenly the OTGW randomly stops.
Connection to the OTMonitor is lost, logging stops, and ch temperature is set to 14 degrees.
Any ideas where to look for an error
Thx,
PPee

**Comment by tjfsteele** [comment]
Can you confirm which version of OTGW you have?

Thank you

>

**Comment by PuckeyP** [comment]
Hi tjfsteel,
Details from the webui - Device Info:
- NodeMCU Firmware Version 0.9.0+21bea01 (06-11-2021)
- OTGW PIC Firmware Version 5.1
- Compiled on (date/time) Nov 6 2021 16:09:58
- Arduino Core Version 2_7_4
- Espressif SDK Version 2.2.2-dev(38a443e)

**Comment by tjfsteele** [comment]
Can you tell me the hardware version? Should be written on the OTGW board
e.g. 2.0

>

**Comment by rvdbreemen** [comment]
@PuckeyP could you share some logging from your OTGW firmware, just telnet to port 23 and capture some logs and share them here. Maybe we can see if anything weird is going on.

**Comment by PuckeyP** [comment]
I attached the complete TelNet log. At 12:00 logging stopped unexpectedly. At 11:43:42 ch_enabled suddenly turned to "OFF"
Hope you can find a indication of the error.

**Comment by PuckeyP** [comment]
[putty.log](https://github.com/rvdbreemen/OTGW-firmware/files/7727206/putty.log)
File attached

**Comment by PuckeyP** [comment]
Hi Robert that is strange, because I did not use hot water this morning. Nobody was home until 13:00...

**Comment by rvdbreemen** [comment]
Hi @PuckeyP well, then that's very weird indeed, but that's what your boiler is reporting back to the OTGW according to your logs. Does your boiler have an error log history?

**Comment by rvdbreemen** [comment]
@PuckeyP just release version 0.9.1 that fixes the OT decoding. So please try that. I will close this issue in the mean time, if you still have problems, then please reopen this issue.
