### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by dvbit** [rvdbreemen/OTGW-firmware#91]
How can I change wifi network once it is setup without refreshing the esp?
Thank You

**Comment by rvdbreemen** [comment]
hi @dvbit 

There are a couple of ways that you can change the WiFi settings:
1. Turning off your WiFi temporary, reboot the ESP.
2. Change your WiFi password (temporary) and reboot your ESP. 

The ESP will go in AP mode again and you can change or setup you WiFi once more.

Either way, you can setup your ESP once more.

Hope this helps,
Robert
