### ISSUE TITLE
Day number off by 1

### ISSUE THREAD

**Issue by arjanwaard** [rvdbreemen/OTGW-firmware#99]
If NTP sync is enabled the day number used in the SC command is off by 1.

**Comment by rvdbreemen** [comment]
That's a good catch, I did notice the spec of OT was different of day of week of iso8601. Simply forgot about it, oops.

Fixed in the dev, just now. Thanks!

**Comment by rvdbreemen** [comment]
@arjanwaard would you like to validate my fix?

**Comment by arjanwaard** [comment]
Sure!
